USE [SalesDB]
GO

SET IDENTITY_INSERT [dbo].[ProductCategory] ON;

INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (1, N'Bikes')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (2, N'Components')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (3, N'Clothing')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (4, N'Accessories')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (5, N'Mountain Bikes')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (6, N'Road Bikes')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (7, N'Touring Bikes')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (8, N'Handlebars')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (9, N'Bottom Brackets')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (10, N'Brakes')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (11, N'Chains')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (12, N'Cranksets')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (13, N'Derailleurs')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (14, N'Forks')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (15, N'Headsets')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (16, N'Mountain Frames')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (17, N'Pedals')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (18, N'Road Frames')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (19, N'Saddles')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (20, N'Touring Frames')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (21, N'Wheels')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (22, N'Bib-Shorts')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (23, N'Caps')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (24, N'Gloves')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (25, N'Jerseys')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (26, N'Shorts')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (27, N'Socks')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (28, N'Tights')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (29, N'Vests')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (30, N'Bike Racks')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (31, N'Bike Stands')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (32, N'Bottles and Cages')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (33, N'Cleaners')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (34, N'Fenders')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (35, N'Helmets')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (36, N'Hydration Packs')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (37, N'Lights')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (38, N'Locks')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (39, N'Panniers')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (40, N'Pumps')
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [Name]) VALUES (41, N'Tires and Tubes')

SET IDENTITY_INSERT [dbo].[ProductCategory] OFF;
